### ISSUE TITLE
Prova

### ISSUE THREAD

**Issue by marcofranceschini** [Kern3lP4nic/RR#1]

**Comment by bertof** [comment]
Notifica arrivata

**Comment by ZanonEdoardo** [comment]
Arrivata

Il 01 dic 2016 16:35, Marco <notifications@github.com> ha scritto:

Assigned #1<https://github.com/Kern3lP4nic/RR/issues/1> to @ZanonEdoardo<https://github.com/ZanonEdoardo>.

**Comment by AntoninoMacri** [comment]
Arrivata

**Comment by jack793** [comment]
prova waffle
